/*

 BACKYARD.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : D:\retro-soccer\tiles\backyard-tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __backyard_h_INCLUDE
#define __backyard_h_INCLUDE

#define BackyardWidth 20
#define BackyardHeight 18
#define BackyardBank 0

extern const unsigned char Backyard[];

#endif

/* End of BACKYARD.H */
