/*

 BACKYARD-TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 47

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : 2 Bits per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __backyard_tiles_h_INCLUDE
#define __backyard_tiles_h_INCLUDE

/* Bank of tiles. */
#define BackyardTilesBank 0

/* Start of tile array. */
extern const unsigned char BackyardTiles[];

#endif

/* End of BACKYARD-TILES.H */
