/*

 ROOM-MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 27 x 23
   Tile set      : D:\retro-soccer\tiles\map-tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __room_map_h_INCLUDE
#define __room_map_h_INCLUDE

#define RoomWidth 27
#define RoomHeight 23
#define RoomBank 0

extern const unsigned char Room[];

#endif

/* End of ROOM-MAP.H */
