/*

 ROOM-MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 27 x 23
   Tile set      : D:\retro-soccer\tiles\map-tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __splash_map_h_INCLUDE
#define __splash_map_h_INCLUDE

#define SplashMapWidth 20
#define SplashMapHeight 18
#define SplashMapBank 0

extern const unsigned char SplashMap[];

#endif

/* End of ROOM-MAP.H */
