char* TEAMS[32] = { 
  "CORINTHIANS",
  "BOTAFOGO",
  "FLAMENGO",
  "SANTOS",
  "VASCO", 
  "LUSA",
  "PALMEIRAS",
  "SAO PAULO",
  "ATLETICO MG",
  "JUVENTUDE",
  "GREMIO",
  "PARANA",
  "INTER",
  "FLUMINENSE",
  "PONTE PRETA",
  "CORITIBA",
  "ATLETICO PR",
  "AMERICA",
  "VITORIA",
  "GURANI",
  "CRUZEIRO",
  "SPORT",
  "CEARA",
  "GOIAS",
  "UNI. S.JOAO",
  "SANTA CRUZ",
  "BRAGANTINO",
  "BAHIA",
  "CRICIUMA",
  "MATONENSE",
  "LONDRINA",
  "JUVENTUS"
};

char* PLAYERS[544] = {
  //CORINTHIANS
  "MAURICIO,G,!",
  "RONALDO,G,!",
  "ANDRE,D,!",
  "ANTONIO C,D,!",
  "FABIO AGST,D,!",
  "RODRIGO,D,!",
  "SANGALETTI,D,!",
  "EDINAN,M,!",
  "ELISON,M,*",
  "F. DINIZ,M,!",
  "RENALDO,M,*",
  "RINCON,M,*",
  "TIBA,M,!",
  "DONIZETE,A,!",
  "MIRANDINHA,A,*",
  "NETO,A,!",
  //BOTAFOGO
  "CARLAO,G,!",
  "WAGNER,G,!",
  "GONCALVES,D,!",
  "JORGE LUIZ,D,!",
  "MARCELO,D,!",
  "PINGo,D,!",
  "W. GOIANO,D,!",
  "ALEMAO,M,!"
  "BENTINHO,M,!",
  "DIMBA,M,*",
  "DJAIR,M,!",
  "M SOUZA,M,!",
  "MARC. ALVES,M,!",
  "BENTINHO,A,!",
  "REINALDO,A,!",
  "SINVAL,A,!",
  "TULIO,A,*"
};
